name: "DEV DEPLOY"

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "dev"
      aws-assume-role-arn: "arn:aws:iam::912880635232:role/github-actions-kelberstuchi-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "kelberstuchi-us-east-1-teraform-pipeline"
      aws-lock-dynamodb-table: "kelberstuchi-us-east-1-terraform-lock"
      